var SPECIES_DATA = {
  "Ardea herodias": {
    range: "Found throughout North America from southern Canada to Mexico and the Caribbean. A year-round resident across all of Florida.",
    habitat: "Extremely adaptable — freshwater marshes, swamps, rivers, lakes, ponds, tidal flats, mangroves, and roadside ditches. Found wherever shallow water holds fish.",
    diet: "Primarily fish, but opportunistically takes frogs, snakes, insects, small mammals, and occasionally other birds. Hunts by standing motionless or walking slowly, then striking with a lightning-fast spear of the bill.",
    fieldMarks: "North America's largest heron at 38–54 in tall with a 6-ft wingspan. Blue-gray body, white head with a black stripe extending into a long black plume, yellowish bill. In flight, the neck folds into an S-curve.",
    behavior: "Solitary forager. Nests colonially in tall trees (rookeries) often shared with egrets and cormorants. Gives a harsh, prehistoric 'frahnk' alarm call when flushed. Highly territorial at feeding sites.",
    conservation: "Least Concern",
    funFact: "A Great Blue Heron can strike prey in a fraction of a second — one of the fastest strikes in the animal kingdom relative to body size.",
  },
  "Ardea alba": {
    range: "Found on every continent except Antarctica. Year-round throughout Florida, with large breeding colonies in the Everglades and central Florida lakes.",
    habitat: "Freshwater and saltwater wetlands including marshes, ponds, rivers, tidal flats, swamps, and flooded fields.",
    diet: "Fish, frogs, snakes, aquatic invertebrates, and small mammals. Wades slowly or stands still in shallow water before striking.",
    fieldMarks: "All white plumage, yellow-orange bill, long black legs. About 38 in tall. During breeding season, develops spectacular lacy aigrette plumes extending beyond the tail and a bright green loral patch.",
    behavior: "Defends feeding territories aggressively. Nests colonially in trees, frequently in mixed-species rookeries alongside herons and ibises.",
    conservation: "Least Concern",
    funFact: "The Great Egret's aigrette plumes were so coveted for hat fashion in the 1800s that the species was nearly hunted to extinction. Outrage over this slaughter helped spark the modern conservation movement and led to the founding of the Audubon Society.",
  },
  "Egretta thula": {
    range: "Throughout North and South America — from southern Canada to Argentina, breeding along both the Atlantic and Pacific coasts of the United States. Common year-round resident in Florida, especially along the coasts.",
    habitat: "Saltwater estuaries, tidal marshes, mangroves, freshwater ponds, swamps, and flooded fields.",
    diet: "Fish, shrimp, crayfish, frogs, and insects. Uses a wide variety of active hunting techniques — shuffling feet to flush prey, running and lunging, spreading wings to attract fish with shade.",
    fieldMarks: "All white, slender build, about 22–26 in tall. Black bill, yellow loral patch, and bright yellow feet on black legs — often called 'golden slippers.' Breeding plumage includes elaborate recurved plumes.",
    behavior: "An energetic and active hunter compared to the patient Great Egret. Can be territorial and competitive at feeding sites. Nests colonially in shrubs or low trees, often with other species.",
    conservation: "Least Concern",
    funFact: "Snowy Egrets have been documented using bait — dropping feathers, insects, or other small objects onto the water surface, then snatching the small fish that come to investigate.",
  },
  "Egretta caerulea": {
    range: "Eastern and Gulf Coast United States to South America. Year-round in Florida, with some northward dispersal by young birds in summer.",
    habitat: "Freshwater ponds, swamps, marshes, rivers, and flooded fields; also coastal estuaries and mangroves.",
    diet: "Fish, frogs, crayfish, insects, and other small aquatic animals. Forages slowly and deliberately, often at vegetation margins.",
    fieldMarks: "Adults are slate-blue with a maroon-purple head and neck and a pale bluish bill with a dark tip. About 22–29 in. Juveniles are entirely white — easily confused with Snowy Egret but lacking yellow feet. Immatures pass through a distinctive pied (patchy blue-and-white) phase.",
    behavior: "More solitary and secretive than many herons. Often forages in dense marsh vegetation. Nests in mixed colonies. The year-long presence of all three plumage stages makes this one of Florida's most visually variable herons.",
    conservation: "Least Concern",
    funFact: "White juvenile Little Blue Herons are tolerated by Snowy Egrets at feeding sites — an advantage that allows them to sneak into productive areas. Once they molt into adult plumage, they're treated as competitors and chased off.",
  },
  "Egretta tricolor": {
    range: "Atlantic and Gulf coasts of North America, Central and South America, and the Caribbean. A year-round resident throughout Florida and one of the most common herons along the coast.",
    habitat: "Primarily coastal — saltwater marshes, mangroves, tidal flats, and estuaries. Less common in freshwater habitats inland.",
    diet: "Overwhelmingly fish, supplemented with frogs, lizards, and crustaceans. One of the most active hunters among Florida herons.",
    fieldMarks: "Dark blue-gray head, neck, and back; white belly and stripe down the foreneck; rusty neck streaking. About 24–30 in with a long, slender neck. The white belly contrasting with the dark back is the key field mark in flight.",
    behavior: "A highly animated, aggressive forager. Charges through shallow water, pivots rapidly, spreads wings, and lunges at prey — far more active than the patient Great Blue Heron. Nests in dense coastal colonies.",
    conservation: "Least Concern",
    funFact: "Despite being one of the smaller herons, the Tricolored Heron is one of Florida's most numerous wading birds — and one of the most entertaining to watch hunt.",
  },
  "Egretta rufescens": {
    range: "Gulf Coast of the United States, Caribbean, Mexico, and Central America. In Florida, primarily found along the Gulf Coast, Tampa Bay, the Florida Keys, and the southern tip of the peninsula.",
    habitat: "Shallow, open saltwater flats, mangrove lagoons, and coastal estuaries. Rarely ventures far from saltwater.",
    diet: "Almost entirely fish. Targets shallow-water species using a spectacular and highly active hunting style unlike any other heron.",
    fieldMarks: "Two color morphs: the dark morph has a slate-gray body with a shaggy reddish-brown head and neck; the rare white morph is all white. Both have a distinctive bicolored bill (pink base, dark tip) and blue-gray legs. About 27–32 in tall.",
    behavior: "Famous for frantic 'canopy feeding' — dashing, lunging, spinning, and spreading wings like an umbrella over the water to reduce glare and startle fish into the open. No other Florida heron hunts quite like it.",
    conservation: "Near Threatened",
    funFact: "The Reddish Egret is one of the rarest herons in North America, with fewer than 2,000 nesting pairs in the United States. Florida's coastal flats are among the best places in the world to observe this species.",
  },
  "Bubulcus ibis": {
    range: "Originally native to sub-Saharan Africa and southern Asia. Spread naturally to South America in the 1800s and reached North America by the 1940s. Now found worldwide; common year-round throughout Florida.",
    habitat: "Dry fields, pastures, roadsides, and agricultural land — very unlike most herons. Follows cattle, horses, tractors, and lawn mowers to catch the insects they flush.",
    diet: "Primarily grasshoppers and other large insects. Also takes frogs, small lizards, and occasionally nestlings. Studies show Cattle Egrets forage 50% more efficiently when following large animals.",
    fieldMarks: "Compact, stocky, all-white egret. Non-breeding birds are pure white with a yellow bill and legs. Breeding adults develop buffy-orange plumes on the head, breast, and back; the bill and legs turn orange-red briefly at peak courtship.",
    behavior: "Highly social — often seen in large flocks. Nests in dense colonies, frequently with other herons and ibises. One of the most successful colonizers in avian history; its global range expansion is still ongoing.",
    conservation: "Least Concern",
    funFact: "Cattle Egrets crossed the Atlantic from Africa to South America on their own in the late 19th century — no human help required. They reached Florida by the 1950s and have become one of the most familiar birds in the state.",
  },
  "Butorides virescens": {
    range: "North and Central America and the Caribbean. Year-round in Florida, particularly common in wooded wetlands and along tree-lined waterways.",
    habitat: "Forested wetlands, mangroves, stream banks, pond edges, and any wooded shoreline with dense overhanging vegetation. Prefers cover and avoids open water.",
    diet: "Fish, frogs, crayfish, insects, and other small invertebrates. Hunts by perching motionless on a low branch or root just above the water and striking downward.",
    fieldMarks: "Small and compact at 16–18 in. Deep greenish-black cap, chestnut neck, dark green-gray back, and short orange-yellow legs (may turn bright orange in breeding season). Often appears hunched at rest.",
    behavior: "Secretive and solitary. When alarmed, stretches neck upward and flicks its tail. One of very few birds known to use tools.",
    conservation: "Least Concern",
    funFact: "Green Herons are among a tiny handful of bird species that use tools. They have been observed manufacturing lures from feathers, leaves, and even bread, then actively repositioning the lure if it drifts away from a good fishing spot.",
  },
  "Nycticorax nycticorax": {
    range: "Found on every continent except Australia and Antarctica. Year-round in Florida, often roosting in large communal groups.",
    habitat: "Freshwater marshes, swamps, mangroves, wooded wetlands, and coastal bays. Roosts and nests in dense vegetation, often in trees directly over water.",
    diet: "Fish, frogs, aquatic invertebrates, insects, and occasionally eggs and chicks of other colonial waterbirds. Will also take small mammals and carrion.",
    fieldMarks: "Stocky with a short neck and a large head. Black cap and back, gray wings, white underparts, red eyes. Two to three long white head plumes in breeding plumage. About 23–26 in. Juveniles are heavily streaked brown.",
    behavior: "Primarily crepuscular and nocturnal — most active at dusk, dawn, and through the night. Roosts communally during the day. Call is a distinctive, barking 'quok' frequently heard near wetlands after dark.",
    conservation: "Least Concern",
    funFact: "Black-crowned Night-Herons have been documented stealing food from other herons, egrets, and even ducks. They have also been observed using bread as bait to catch fish — one of only a handful of herons known to fish with lures.",
  },
  "Nyctanassa violacea": {
    range: "Eastern North America, the Caribbean, Central America, and parts of South America. Year-round in Florida, especially common in coastal and mangrove habitats.",
    habitat: "Mangroves, coastal marshes, tidal flats, wooded swamps, and estuaries. More closely tied to saltwater and brackish environments than the Black-crowned Night-Heron.",
    diet: "A specialist in crustaceans — primarily crabs, crayfish, and shrimp. Also takes fish, insects, frogs, and small vertebrates. Its heavier, more powerful bill is adapted for crushing hard-shelled prey.",
    fieldMarks: "Gray body, bold black-and-white facial pattern, pale yellow crown stripe (brightest in breeding adults). Stocky like the Black-crowned, but with a longer neck, longer legs, and a heavier bill. About 21–28 in. Juveniles are dark brown with fine white streaking.",
    behavior: "More crepuscular than fully nocturnal — often active through the day along mangrove edges. Typically more solitary than the Black-crowned. Nests in mangroves and coastal trees.",
    conservation: "Least Concern",
    funFact: "Yellow-crowned Night-Herons can expertly dismantle crabs — breaking off the claws and legs, crushing the carapace, and swallowing the pieces. They have been observed working on a single crab for several minutes before consuming it.",
  },
  "Ardea herodias occidentalis": {
    range: "Found almost exclusively in the Florida Keys, Florida Bay, and the coastal mangroves of extreme southern Florida — the most geographically restricted heron in North America. Rarely wanders to the Gulf Coast or the Dry Tortugas.",
    habitat: "Open saltwater bays, tidal flats, mangrove shorelines, and shallow coastal waters. Almost never found in freshwater environments.",
    diet: "Primarily large fish. Hunts with the same patient, stand-and-wait style as the Great Blue Heron, but almost exclusively in marine environments.",
    fieldMarks: "All white plumage and the same massive size as the Great Blue Heron (38–54 in, 6-ft wingspan) — making it the largest all-white heron in Florida. Yellow bill, pale yellow legs. Lacks the dark legs of the Great Egret.",
    behavior: "Generally less wary than Great Blue Herons and may allow a close approach. Tends to be solitary. Often seen wading on expansive open tidal flats. Most taxonomists treat it as a white color morph of Ardea herodias rather than a full species.",
    conservation: "Special Concern (Florida)",
    funFact: "The Great White Heron is not an albino — it is a genetically distinct white morph found only in the hyper-saline environments of extreme South Florida. It occasionally interbreeds with the Great Blue Heron, producing a rare intermediate form called the 'Würdemann's Heron.'",
  },
  "Ixobrychus exilis": {
    range: "Eastern and central North America, Central America, and parts of South America. Year-round in Florida, though easily overlooked due to its secretive habits.",
    habitat: "Dense freshwater marshes dominated by tall emergent vegetation — cattails, bulrushes, and giant reed. Requires thick stands of reeds for cover and almost never ventures into the open.",
    diet: "Primarily small fish, frogs, and insects. Hunts by perching on reed stems directly above the water and striking downward.",
    fieldMarks: "North America's smallest heron at just 11–14 in — barely larger than a Red-winged Blackbird. Buff underparts, chestnut neck, large pale buff wing patches. Males have a black cap and back; females are streaked brown. Greenish-yellow bill and legs.",
    behavior: "Extraordinarily secretive. Climbs through reeds using its large grasping feet. When alarmed, freezes with bill pointed skyward, blending perfectly into the stems. Far more often heard (a low cooing call) than seen.",
    conservation: "Least Concern",
    funFact: "Least Bitterns can compress their bodies to fit through gaps between reed stems that seem impossibly narrow. This 'reed-walking' ability, gripping two stems simultaneously and inching between them, is unique among North American herons.",
  },
};

// Edit these to add or change photos.
// Duplicate an entry to add a photo. Remove an entry to remove it.
// - id:          stable integer — never change or reuse once assigned
// - src:         full image URL
// - alt:         describe the photo (used in lightbox caption)
// - is_featured: true = shows in the homepage carousel
// - project:     project slug, e.g. "herons" — adds photo to that project gallery
// - species:     scientific name, e.g. "Ardea herodias" — links photo to species card
// - location:    location slug, e.g. "sweetwater-wetland-preserve" — adds photo to a place gallery
// - usage:       special page use, e.g. "about" — keeps a photo in admin but out of public galleries
var LOCATIONS_DATA = [
  {
    slug: "sweetwater-wetland-preserve",
    name: "Sweetwater Wetland Preserve",
    region: "Gainesville, Florida",
    status: "First location",
    summary: "A continuing collection from the boardwalks, marsh edges, and open water at Sweetwater Wetland Preserve.",
    description: "A place-based gallery for photographs made while walking Sweetwater Wetland Preserve in Gainesville — wetland birds, quiet habitat details, and the patient scenes that unfold between the reeds.",
    coverImageId: 11,
  },
  {
    slug: "silver-river",
    name: "Silver River",
    region: "Silver Springs, Florida",
    status: "River location",
    summary: "A collection from the clear water, cypress banks, and wild edges of Silver River upstream from Ray Wayside Park.",
    description: "A place-based gallery for photographs made on Silver River while traveling upstream from Ray Wayside Park toward Silver Springs — clear spring water, shaded banks, and the wildlife encountered along the run.",
  },
];

var GALLERY_IMAGES = [
  {
    id: 1,
    src: "https://live.staticflickr.com/65535/55275393790_e70c958e89_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "silver-river",
  },
  {
    id: 2,
    src: "https://live.staticflickr.com/65535/55274997711_a476e4b222_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "silver-river",
  },
  {
    id: 3,
    src: "https://live.staticflickr.com/65535/55275129113_70d94a57ca_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "silver-river",
  },
  {
    id: 4,
    src: "https://live.staticflickr.com/65535/55275393450_ec5b55797a_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "silver-river",
  },
  {
    id: 5,
    src: "https://live.staticflickr.com/65535/55274080112_6213a4d98d_b.jpg",
    alt: "Yellow-crowned Night-Heron",
    is_featured: true,
    project: "herons",
    location: "silver-river",
    species: "Nyctanassa violacea",
  },
  {
    id: 6,
    src: "https://live.staticflickr.com/65535/55275128673_79dac08b00_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "silver-river",
  },
  {
    id: 7,
    src: "https://live.staticflickr.com/65535/55250254275_f0fc9c0970_b.jpg",
    alt: "Brandon Alley - photographer",
    is_featured: false,
    usage: "about",
  },
  {
    id: 8,
    src: "https://live.staticflickr.com/65535/55174862805_526015f4ef_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 9,
    src: "https://live.staticflickr.com/65535/55268958145_c1c8cb087b_b.jpg",
    alt: "Yellow-crowned Night-Heron",
    is_featured: true,
    project: "herons",
    location: "silver-river",
    species: "Nyctanassa violacea",
  },
  {
    id: 10,
    src: "https://live.staticflickr.com/65535/55268957900_7aff49f7d3_b.jpg",
    alt: "Little Blue Heron",
    is_featured: true,
    project: "herons",
    location: "silver-river",
    species: "Egretta caerulea",
  },
  {
    id: 11,
    src: "https://live.staticflickr.com/65535/55267648392_f20c890bff_b.jpg",
    alt: "Great Blue Heron",
    is_featured: true,
    project: "herons",
    species: "Ardea herodias",
  },
  {
    id: 12,
    src: "https://live.staticflickr.com/65535/55269065449_aafc10cc7a_b.jpg",
    alt: "Snowy Egret",
    is_featured: true,
    project: "herons",
    species: "Egretta thula",
  },
  {
    id: 13,
    src: "https://live.staticflickr.com/65535/55249900291_eb9c82c3df_b.jpg",
    alt: "Great Egret",
    is_featured: true,
    project: "herons",
    species: "Ardea alba",
  },
  {
    id: 14,
    src: "https://live.staticflickr.com/65535/55249990758_8bf1386914_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 15,
    src: "https://live.staticflickr.com/65535/55249847956_9420a2b4ba_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 16,
    src: "https://live.staticflickr.com/65535/55225222323_4a86a6f175_b.jpg",
    alt: "Jae & Sandra Vow Renewal",
    is_featured: true,
  },
  {
    id: 17,
    src: "https://live.staticflickr.com/65535/55201917211_89fd523944_b.jpg",
    alt: "Snowy Egret",
    is_featured: true,
    project: "herons",
    species: "Egretta thula",
  },
  {
    id: 18,
    src: "https://live.staticflickr.com/65535/55198152423_a55f5c0f74_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 19,
    src: "https://live.staticflickr.com/65535/55198253354_35cd84e9f9_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 20,
    src: "https://live.staticflickr.com/65535/55197113802_cb0715fa72_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 21,
    src: "https://live.staticflickr.com/65535/55198151633_86139082e9_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 22,
    src: "https://live.staticflickr.com/65535/55174718119_fcc96e9679_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 23,
    src: "https://live.staticflickr.com/65535/55174717824_1760dae358_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 24,
    src: "https://live.staticflickr.com/65535/55141237211_d22ab4de9a_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 25,
    src: "https://live.staticflickr.com/65535/55139720299_2e23294ac7_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
  },
  {
    id: 26,
    src: "https://live.staticflickr.com/65535/55283597631_8baf6451e3_b.jpg",
    alt: "Great Blue Heron",
    is_featured: true,
    project: "herons",
    location: "sweetwater-wetland-preserve",
    species: "Ardea herodias",
  },
  {
    id: 27,
    src: "https://live.staticflickr.com/65535/55282678262_b9e76f6883_b.jpg",
    alt: "Black-crowned Night-Heron",
    is_featured: true,
    project: "herons",
    location: "sweetwater-wetland-preserve",
    species: "Nycticorax nycticorax",
  },
  {
    id: 28,
    src: "https://live.staticflickr.com/65535/55283738983_c5ba4ef8dd_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 29,
    src: "https://live.staticflickr.com/65535/55284001095_b95ecfb0ac_b.jpg",
    alt: "Green Heron",
    is_featured: true,
    project: "herons",
    location: "sweetwater-wetland-preserve",
    species: "Butorides virescens",
  },
  {
    id: 30,
    src: "https://live.staticflickr.com/65535/55283968819_0fa0d99313_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 31,
    src: "https://live.staticflickr.com/65535/55283736581_167df13cfa_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 32,
    src: "https://live.staticflickr.com/65535/55283879263_9582d48133_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 33,
    src: "https://live.staticflickr.com/65535/55282818817_1bbcffccc3_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 34,
    src: "https://live.staticflickr.com/65535/55283878928_4f259f5d22_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 35,
    src: "https://live.staticflickr.com/65535/55283967969_aa36e9694a_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 36,
    src: "https://live.staticflickr.com/65535/55283735911_f345dec018_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 37,
    src: "https://live.staticflickr.com/65535/55284141365_3145f46924_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 38,
    src: "https://live.staticflickr.com/65535/55283878458_d625753997_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 39,
    src: "https://live.staticflickr.com/65535/55283878413_398fdbb8f5_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 40,
    src: "https://live.staticflickr.com/65535/55283878268_e0df3ec914_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 41,
    src: "https://live.staticflickr.com/65535/55283735431_d2711f1035_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 42,
    src: "https://live.staticflickr.com/65535/55283878123_1fe399caf3_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: true,
    location: "sweetwater-wetland-preserve",
  },
  {
    id: 43,
    src: "https://live.staticflickr.com/65535/55305852735_69175cfc76_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: false,
  },
  {
    id: 44,
    src: "https://live.staticflickr.com/65535/55304540062_e03d7d65eb_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: false,
  },
  {
    id: 45,
    src: "https://live.staticflickr.com/65535/55305852450_36b2693b9b_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: false,
  },
  {
    id: 46,
    src: "https://live.staticflickr.com/65535/55305677989_996cc83289_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: false,
  },
  {
    id: 47,
    src: "https://live.staticflickr.com/65535/55305597813_f25081a18e_b.jpg",
    alt: "Photography by Brandon Alley",
    is_featured: false,
  },
];

var FLICKR_METADATA = {
  1: { flickrId: "55275393790", title: "BrandonAlleyPhotography_SiliverSprings_202605101269.jpg", dateTaken: "2026-05-10 17:32:23", width: "1024", height: "683" },
  2: { flickrId: "55274997711", title: "BrandonAlleyPhotography_SiliverSprings_202605101219.jpg", dateTaken: "2026-05-10 17:28:51", width: "1024", height: "683" },
  3: { flickrId: "55275129113", title: "BrandonAlleyPhotography_SiliverSprings_20260510946.jpg", dateTaken: "2026-05-10 16:58:14", width: "1024", height: "683" },
  4: { flickrId: "55275393450", title: "BrandonAlleyPhotography_SiliverSprings_20260510706.jpg", dateTaken: "2026-05-10 16:08:25", width: "1024", height: "683" },
  5: { flickrId: "55274080112", title: "BrandonAlleyPhotography_SiliverSprings_20260510596.jpg", dateTaken: "2026-05-10 15:50:17", width: "683", height: "1024" },
  6: { flickrId: "55275128673", title: "BrandonAlleyPhotography_SiliverSprings_20260510539.jpg", dateTaken: "2026-05-10 15:44:35", width: "1024", height: "683" },
  7: { flickrId: "55250254275", title: "BrandonAlleyPhotography_untitled shoot_2026050221.jpg", dateTaken: "2026-05-02 16:46:09", width: "819", height: "1024" },
  8: { flickrId: "55174862805", title: "AlleyPhotography_IMG_3887.jpg", dateTaken: "2026-03-28 12:11:19", width: "683", height: "1024" },
  9: { flickrId: "55268958145", title: "BrandonAlleyPhotography_SiliverSprings_202605101183.jpg", dateTaken: "2026-05-10 17:25:10", width: "1024", height: "683" },
  10: { flickrId: "55268957900", title: "BrandonAlleyPhotography_SiliverSprings_20260510598.jpg", dateTaken: "2026-05-10 15:53:36", width: "683", height: "1024" },
  11: { flickrId: "55267648392", title: "BrandonAlleyPhotography_untitled shoot_2026050939.jpg", dateTaken: "2026-05-09 13:55:37", width: "683", height: "1024" },
  12: { flickrId: "55269065449", title: "BrandonAlleyPhotography-4652", dateTaken: "2026-04-08 10:47:48", width: "1024", height: "683" },
  13: { flickrId: "55249900291", title: "BrandonAlleyPhotography-4347.jpg", dateTaken: "2026-04-08 10:26:44", width: "1024", height: "683" },
  14: { flickrId: "55249990758", title: "BrandonAlleyPhotography_untitled shoot_20260423170.jpg", dateTaken: "2026-04-23 16:28:08", width: "1024", height: "683" },
  15: { flickrId: "55249847956", title: "BrandonAlleyPhotography_untitled shoot_20260423278.jpg", dateTaken: "2026-04-23 16:59:15", width: "1024", height: "683" },
  16: { flickrId: "55225222323", title: "BrandonAlleyPhotography_Jae&SandraVowRenewal_20260418248.jpg", dateTaken: "2026-04-18 16:55:48", width: "731", height: "1024" },
  17: { flickrId: "55201917211", title: "AlleyPhotography_IMG_4647-Edit.jpg", dateTaken: "2026-04-08 10:47:25", width: "1024", height: "683" },
  18: { flickrId: "55198152423", title: "AlleyPhotography_IMG_4568.jpg", dateTaken: "2026-04-08 10:42:09", width: "1024", height: "683" },
  19: { flickrId: "55198253354", title: "AlleyPhotography_IMG_4295.jpg", dateTaken: "2026-04-08 10:10:06", width: "1024", height: "683" },
  20: { flickrId: "55197113802", title: "AlleyPhotography_IMG_4197.jpg", dateTaken: "2026-04-08 10:02:36", width: "1024", height: "683" },
  21: { flickrId: "55198151633", title: "AlleyPhotography_IMG_4181.jpg", dateTaken: "2026-04-08 10:00:42", width: "1024", height: "683" },
  22: { flickrId: "55174718119", title: "AlleyPhotography_IMG_3998.jpg", dateTaken: "2026-03-28 12:15:28", width: "683", height: "1024" },
  23: { flickrId: "55174717824", title: "BrandonAlleyPhotography-0091.jpg", dateTaken: "2026-03-13 18:14:54", width: "1024", height: "683" },
  24: { flickrId: "55141237211", title: "TheAlleyPhotography.jpg", dateTaken: "2026-03-07 18:32:08", width: "769", height: "1024" },
  25: { flickrId: "55139720299", title: "BrandonAlleyPhotography-8451.jpg", dateTaken: "2026-03-07 18:27:15", width: "1024", height: "683" },
  26: { flickrId: "55283597631", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517611.jpg", dateTaken: "2026-05-17 18:52:24", width: "683", height: "1024" },
  27: { flickrId: "55282678262", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517438.jpg", dateTaken: "2026-05-17 18:26:16", width: "1024", height: "683" },
  28: { flickrId: "55283738983", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517429.jpg", dateTaken: "2026-05-17 18:25:34", width: "683", height: "1024" },
  29: { flickrId: "55284001095", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517411.jpg", dateTaken: "2026-05-17 18:23:24", width: "1024", height: "683" },
  30: { flickrId: "55283968819", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_202605171045.jpg", dateTaken: "2026-05-17 19:46:45", width: "1024", height: "683" },
  31: { flickrId: "55283736581", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_202605171038.jpg", dateTaken: "2026-05-17 19:45:46", width: "1024", height: "683" },
  32: { flickrId: "55283879263", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_202605171036.jpg", dateTaken: "2026-05-17 19:45:32", width: "1024", height: "683" },
  33: { flickrId: "55282818817", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_202605171029.jpg", dateTaken: "2026-05-17 19:44:32", width: "1024", height: "683" },
  34: { flickrId: "55283878928", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517972.jpg", dateTaken: "2026-05-17 19:34:31", width: "683", height: "1024" },
  35: { flickrId: "55283967969", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517967.jpg", dateTaken: "2026-05-17 19:33:39", width: "1024", height: "683" },
  36: { flickrId: "55283735911", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517561.jpg", dateTaken: "2026-05-17 18:43:57", width: "1024", height: "683" },
  37: { flickrId: "55284141365", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517549.jpg", dateTaken: "2026-05-17 18:43:10", width: "1024", height: "683" },
  38: { flickrId: "55283878458", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517474.jpg", dateTaken: "2026-05-17 18:28:16", width: "1024", height: "683" },
  39: { flickrId: "55283878413", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_20260517181.jpg", dateTaken: "2026-05-17 17:58:54", width: "1024", height: "683" },
  40: { flickrId: "55283878268", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_2026051771.jpg", dateTaken: "2026-05-17 15:02:58", width: "1024", height: "683" },
  41: { flickrId: "55283735431", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_2026051751.jpg", dateTaken: "2026-05-17 15:00:09", width: "1024", height: "683" },
  42: { flickrId: "55283878123", title: "BrandonAlleyPhotography_SweetwaterWetlandPark_2026051740.jpg", dateTaken: "2026-05-17 14:59:48", width: "1024", height: "683" },
  43: { flickrId: "55305852735", title: "BrandonAlleyPhotography_untitled shoot_202605211418.jpg", dateTaken: "2026-05-21 19:22:19", width: "819", height: "1024" },
  44: { flickrId: "55304540062", title: "BrandonAlleyPhotography_untitled shoot_202605211263.jpg", dateTaken: "2026-05-21 19:11:43", width: "1024", height: "683" },
  45: { flickrId: "55305852450", title: "BrandonAlleyPhotography_untitled shoot_20260521767.jpg", dateTaken: "2026-05-21 15:20:02", width: "683", height: "1024" },
  46: { flickrId: "55305677989", title: "BrandonAlleyPhotography_untitled shoot_20260521511.jpg", dateTaken: "2026-05-21 15:07:54", width: "1024", height: "683" },
  47: { flickrId: "55305597813", title: "BrandonAlleyPhotography_untitled shoot_20260521500.jpg", dateTaken: "2026-05-21 15:07:39", width: "1024", height: "683" },
};

var FLICKR_CAMERA_METADATA = {
  1: { camera: "Canon EOS R100", shutter: "1/200", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  2: { camera: "Canon EOS R100", shutter: "1/200", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  3: { camera: "Canon EOS R100", shutter: "1/200", iso: "800", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  4: { camera: "Canon EOS R100", shutter: "1/200", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  5: { camera: "Canon EOS R100", shutter: "1/200", iso: "400", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  6: { camera: "Canon EOS R100", shutter: "1/1250", iso: "800", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  7: { camera: "Canon EOS R100", lens: "RF50mm F1.8 STM", shutter: "1/40", aperture: "f/1.8", iso: "100", focalLength: "50.0 mm", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  8: { camera: "Canon EOS R100", shutter: "1/1000", iso: "1600", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  9: { camera: "Canon EOS R100", shutter: "1/200", iso: "200", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  10: { camera: "Canon EOS R100", shutter: "1/160", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  11: { camera: "Canon EOS R100", lens: "RF50mm F1.8 STM", shutter: "1/1600", aperture: "f/1.8", iso: "100", focalLength: "50.0 mm", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  12: { camera: "Canon EOS R100", shutter: "1/4000", iso: "400", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  13: { camera: "Canon EOS R100", lens: "RF-S18-45mm F4.5-6.3 IS STM", shutter: "1/1600", aperture: "f/6.3", iso: "100", focalLength: "45.0 mm", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  14: { camera: "Canon EOS R100", lens: "RF50mm F1.8 STM", shutter: "1/320", aperture: "f/2.8", iso: "100", focalLength: "50.0 mm", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  15: { camera: "Canon EOS R100", shutter: "1/800", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  16: { camera: "Canon EOS R100", lens: "RF-S18-45mm F4.5-6.3 IS STM", shutter: "1/125", aperture: "f/6.3", iso: "100", focalLength: "35.0 mm", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  17: { camera: "Canon EOS R100", shutter: "1/4000", iso: "400", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  18: { camera: "Canon EOS R100", shutter: "1/125", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  19: { camera: "Canon EOS R100", shutter: "1/800", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  20: { camera: "Canon EOS R100", shutter: "1/4000", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  21: { camera: "Canon EOS R100", shutter: "1/4000", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  22: { camera: "Canon EOS R100", shutter: "1/200", iso: "200", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  23: { camera: "Canon EOS R100", lens: "RF-S18-45mm F4.5-6.3 IS STM", shutter: "1/100", aperture: "f/7.1", iso: "200", focalLength: "45.0 mm", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Manual" },
  24: { camera: "Canon EOS 20D", lens: "18.0-55.0 mm", shutter: "1/80", aperture: "f/6.3", iso: "400", focalLength: "55.0 mm", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Average", whiteBalance: "Manual" },
  25: { camera: "Canon EOS 20D", lens: "18.0-55.0 mm", shutter: "1/80", aperture: "f/5.6", iso: "400", focalLength: "54.0 mm", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Average", whiteBalance: "Manual" },
  26: { camera: "Canon EOS R100", shutter: "1/500", iso: "500", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  27: { camera: "Canon EOS R100", shutter: "1/640", iso: "1250", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  28: { camera: "Canon EOS R100", shutter: "1/640", iso: "1000", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  29: { camera: "Canon EOS R100", shutter: "1/200", iso: "250", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  30: { camera: "Canon EOS R100", shutter: "1/640", iso: "1600", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  31: { camera: "Canon EOS R100", shutter: "1/640", iso: "1600", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  32: { camera: "Canon EOS R100", shutter: "1/640", iso: "1600", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  33: { camera: "Canon EOS R100", shutter: "1/640", iso: "1600", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  34: { camera: "Canon EOS R100", shutter: "1/640", iso: "640", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  35: { camera: "Canon EOS R100", shutter: "1/640", iso: "500", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  36: { camera: "Canon EOS R100", shutter: "1/160", iso: "500", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  37: { camera: "Canon EOS R100", shutter: "1/160", iso: "125", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  38: { camera: "Canon EOS R100", shutter: "1/640", iso: "1600", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  39: { camera: "Canon EOS R100", shutter: "1/1000", iso: "1600", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  40: { camera: "Canon EOS R100", shutter: "1/250", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  41: { camera: "Canon EOS R100", shutter: "1/200", iso: "500", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  42: { camera: "Canon EOS R100", shutter: "1/200", iso: "500", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  43: { camera: "Canon EOS R100", lens: "RF50mm F1.8 STM", shutter: "1/80", aperture: "f/22.0", iso: "160", focalLength: "50 mm", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  44: { camera: "Canon EOS R100", lens: "RF50mm F1.8 STM", shutter: "1/640", aperture: "f/2.8", iso: "100", focalLength: "50 mm", flash: "Flash (off, did not fire)", exposureMode: "Manual", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  45: { camera: "Canon EOS R100", shutter: "1/4000", iso: "250", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  46: { camera: "Canon EOS R100", shutter: "1/4000", iso: "125", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
  47: { camera: "Canon EOS R100", shutter: "1/4000", iso: "100", flash: "Flash (off, did not fire)", exposureMode: "Auto", meteringMode: "Multi-segment", whiteBalance: "Auto" },
};
